; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:hand_firmware]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitm-1
framework = espidf
board_build.partitions = hand_partition.csv
lib_deps = nanopb/Nanopb@^0.4.91
lib_extra_dirs = lib/devices
monitor_filters = direct, esp32_exception_decoder
build_type = debug
build_flags = 
	-I include
	
	
	-DLIB_PLATFORM=espidf
	-DLIB_BSP_BOARD=hand
	
	-DLIB_USE_ESPIDF_PLATFORM
	
	
	
	-DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE
platform_packages = 
	platformio/framework-espidf@3.50201.240515
extra_scripts = 
	pre:scripts/package_install.py
	scripts/hand_hook.py

[env:hand_test]
extends = env:hand_firmware
build_flags = 
	${env:hand_firmware.build_flags}
	
	-DTEST_HAND_TCP_ECHO_SERVER_IP=\"172.20.10.2\"
	-DTEST_HAND_WIFI_SSID=\"GaraGara\"
	-DTEST_HAND_WIFI_PASSWORD=\"1234567890\"
test_build_src = false
test_filter = test_vl53l1x_id
extra_scripts = 
	pre:scripts/package_install.py
	scripts/hand_test_hook.py
lib_deps = nanopb/Nanopb@^0.4.91
