/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "src/hand_modules/hand_data/proto/hand_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HandDataMsg, HandDataMsg, AUTO)


PB_BIND(HandConfigMsg, HandConfigMsg, AUTO)


PB_BIND(HandCmdMsg, HandCmdMsg, AUTO)


PB_BIND(HandDataWrapper, HandDataWrapper, AUTO)


PB_BIND(HandConfigWrapper, HandConfigWrapper, AUTO)


PB_BIND(HandCmdWrapper, HandCmdWrapper, AUTO)


PB_BIND(HandMsg, HandMsg, AUTO)













